%% training data
clc
clear all
training_folder = uigetdir;
training_data_total = imageDatastore(training_folder,'IncludeSubfolders',true,'LabelSource','foldernames');
[train,validate] = splitEachLabel(training_data_total,4168,'randomized');
%%
net = resnet101;
lgraph = layerGraph(net);
%{
figure('Units','normalized','Position',[0.1 0.1 0.8 0.8]);
plot(lgraph)
%}
lgraph = removeLayers(lgraph, {'prob','ClassificationLayer_predictions'});
newLayers = [
    dropoutLayer(0.5,'Name','dropoutlayer_new1')
    fullyConnectedLayer(1000,'Name','new_fc1000')
    dropoutLayer(0.5,'Name','dropoutlayer_new2')
    fullyConnectedLayer(100,'Name','new_fc100')
    dropoutLayer(0.5,'Name','dropoutlayer_new3')
    fullyConnectedLayer(3,'Name','fc_new','WeightLearnRateFactor',10,'BiasLearnRateFactor',10)
    softmaxLayer('Name','softmax')
    classificationLayer('Name','classoutput')];
lgraph = addLayers(lgraph,newLayers);
lgraph = connectLayers(lgraph,'fc1000','dropoutlayer_new1');
%figure('Units','normalized','Position',[0.3 0.3 0.4 0.4]);
%plot(lgraph)
%ylim([0,10])
%% freeze layers
layers = lgraph.Layers;
connections = lgraph.Connections;
%layers(1:311) = freezeWeights(layers(1:311));% up to res4b22 layer, except for res5a,b,c modules
layers(1:333) = freezeWeights(layers(1:333));% up to res5b layer, except for last res modules
lgraph = createLgraphUsingConnections(layers,connections);
%% data augmentation
%{
pixelRange = [-20 20];
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);
augimdsTrain = augmentedImageDatastore([224 224],train, ...
    'DataAugmentation',imageAugmenter);
%}
%%
%{
opts = trainingOptions('sgdm', ...
    'InitialLearnRate',0.1, ...
    'MaxEpochs',2000,...
    'MiniBatchSize',128,...
    'ValidationData',validate,...
    'ValidationFrequency',40,...
    'LearnRateDropFactor',0.1,...
    'LearnRateDropPeriod',50,...
    'Verbose',false ,...
    'ExecutionEnvironment','multi-gpu',...
    'Plots','training-progress');
%}
%{
opts = trainingOptions('sgdm', ...
    'InitialLearnRate',0.0001, ...
    'MaxEpochs',2000,...
    'MiniBatchSize',256,...
    'ValidationData',validate,...
    'ValidationFrequency',50,...
    'ValidationPatience',10,...
    'Verbose',false ,...
    'LearnRateDropFactor',0.5,...
    'LearnRateDropPeriod',500,...
    'ExecutionEnvironment','multi-gpu',...
    'Plots','training-progress');
%}
opts = trainingOptions('adam', ...
    'InitialLearnRate',0.001, ...
    'MaxEpochs',200,...
    'MiniBatchSize',256,...
    'Verbose',true,...
    'GradientDecayFactor',0.9,...
    'SquaredGradientDecayFactor',0.999,...
    'Epsilon',0.01,...
    'ExecutionEnvironment','multi-gpu',...
    'Plots','training-progress');
[resnetUS,info] = trainNetwork(train, lgraph, opts);
model_name='resnet_case1_20_80_50%sliding_high_intensity_more_dropout.mat';
model_folder= '../trained models/11062018';
model=fullfile(model_folder,model_name);
save (model,'resnetUS')

