%% Retrain resnet
% Read data and split data into training,validating,testing groups
clc
clear all
training_folder = uigetdir;
training_data_total = imageDatastore(training_folder,'IncludeSubfolders',true,'LabelSource','foldernames');
training_data_total = shuffle(training_data_total);
[train,leftdata] = splitEachLabel(training_data_total,1788,'randomized');
%leftdata = shuffle(leftdata);
%[validate,test]=splitEachLabel(leftdata,200,'randomized');
% load the model to be fine tuned
model_folder= '../trained models/11062018';
addpath(model_folder);
model_name = 'resnet_case1video4_20_80_high_intensity_balanced.mat';
model_file=fullfile(model_folder,model_name);
load (model_file);
net = resnetUS;
lgraph = layerGraph(net);
% freeze layers
layers = lgraph.Layers;
connections = lgraph.Connections;
layers(1:311) = freezeWeights(layers(1:311));
%layers(1:39) = freezeWeights(layers(1:39));
lgraph = createLgraphUsingConnections(layers,connections);
% data augmentation
imageAugmenter = imageDataAugmenter('RandRotation',[-30 30]);
%'RandXReflection',true
augimdsTrain = augmentedImageDatastore([224 224],train, ...
    'DataAugmentation',imageAugmenter);
% training options:
opts = trainingOptions('adam', ...
    'InitialLearnRate',0.0003, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropFactor',0.1,...
    'LearnRateDropPeriod',15,...
    'MaxEpochs',50,...
    'MiniBatchSize',64,...
    'Verbose',true,...
    'GradientDecayFactor',0.9,...
    'SquaredGradientDecayFactor',0.999,...
    'Epsilon',0.01,...
    'ExecutionEnvironment','multi-gpu',...
    'CheckpointPath','C:\Users\NeuroBeast\Desktop\network_checkpoints',...
    'Plots','training-progress');
%{
    'ValidationData',validate,...
    'ValidationFrequency',50,...
    'ValidationPatience',Inf,...
    %}
[resnetUS,info] = trainNetwork(augimdsTrain,lgraph,opts);
model_name_saved='retrain_resnet101_20180630_01.mat';
model_folder_saved= '../trained models/20180623';
model=fullfile(model_folder_saved,model_name_saved);
save (model,'resnetUS','info')
%% locate the 
