clc
clear all
training_folder = uigetdir;
training_data_total = imageDatastore(training_folder,'IncludeSubfolders',true,'LabelSource','foldernames');
[train,validate] = splitEachLabel(training_data_total,5500,'randomized');
%% model:
model_name='Googlenet_case1_5000_square_50%sliding_HighIntensity_AugmentationCase1Video4Healthy.mat';
model_folder= '../trained models/18062018';
addpath(model_folder);
model=fullfile(model_folder,model_name);
load(model);
neural_net = googlenetUS;
lgraph = layerGraph(neural_net);%
layers = lgraph.Layers;
connections = lgraph.Connections;
layers(1:96) = freezeWeights(layers(1:96));
lgraph = createLgraphUsingConnections(layers,connections);
%%
opts = trainingOptions('adam', ...
    'InitialLearnRate',0.001, ...
    'MaxEpochs',30,...
    'MiniBatchSize',256,...
    'Verbose',true,...
    'GradientDecayFactor',0.9,...
    'SquaredGradientDecayFactor',0.999,...
    'Epsilon',0.01,...
    'ValidationData',validate,...
    'ValidationFrequency',50,...
    'ValidationPatience',Inf,...
    'ExecutionEnvironment','multi-gpu',...
    'Plots','training-progress');
[googlenetUS,info] = trainNetwork(train,lgraph, opts);
model_name='More_epoches_Googlenet_case1_5000_square_50%sliding_HighIntensity_AugmentationCase1Video4Healthy.mat';
model_folder= '../trained models/18062018';
model=fullfile(model_folder,model_name);
save (model,'googlenetUS','info')